fix

diff --git a/tasks/gatk4_m2_maflite/gatk4_m2_maflite_task_1/Dockerfile b/tasks/gatk4_m2_maflite/gatk4_m2_maflite_task_1/Dockerfile
--- a/tasks/gatk4_m2_maflite/gatk4_m2_maflite_task_1/Dockerfile
+++ b/tasks/gatk4_m2_maflite/gatk4_m2_maflite_task_1/Dockerfile
@@ -1,42 +1,78 @@
 FROM ubuntu:16.04
 
-RUN apt-get update && apt-get install -y python sudo dstat wget zlib1g zlib1g-dev
-
-RUN apt-get update \
-	&& apt-get install -y --no-install-recommends ca-certificates \
-	&& rm -rf /var/lib/apt/lists/*
+RUN set -eux; \
+	apt-get update; \
+	apt-get install -y --no-install-recommends \
+		ca-certificates \
+# ERROR: no download agent available; install curl, wget, or fetch
+		curl \
+	; \
+	rm -rf /var/lib/apt/lists/*
 
 ENV JULIA_PATH /usr/local/julia
-ENV JULIA_VERSION 1.0.0
-
-RUN mkdir $JULIA_PATH \
-	&& apt-get update && apt-get install -y curl \
-	&& curl -sSL "https://julialang.s3.amazonaws.com/bin/linux/x64/${JULIA_VERSION%[.-]*}/julia-${JULIA_VERSION}-linux-x86_64.tar.gz" -o julia.tar.gz \
-	&& curl -sSL "https://julialang.s3.amazonaws.com/bin/linux/x64/${JULIA_VERSION%[.-]*}/julia-${JULIA_VERSION}-linux-x86_64.tar.gz.asc" -o julia.tar.gz.asc \
-	&& export GNUPGHOME="$(mktemp -d)" \
-# http://julialang.org/juliareleases.asc
-# Julia (Binary signing key) <buildbot@julialang.org>
-	&& gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 3673DF529D9049477F76B37566E3C7DC03D6E495 \
-	&& gpg --batch --verify julia.tar.gz.asc julia.tar.gz \
-	&& rm -r "$GNUPGHOME" julia.tar.gz.asc \
-	&& tar -xzf julia.tar.gz -C $JULIA_PATH --strip-components 1 \
-	&& rm -rf /var/lib/apt/lists/* julia.tar.gz*
-
-
 ENV PATH $JULIA_PATH/bin:$PATH
 
-RUN julia -e 'Pkg.add("DataFrames")'
-RUN julia -e 'Pkg.build("DataFrames")'
-RUN julia -e 'Pkg.add("CSV")'
-RUN julia -e 'Pkg.add("Statistics")'
-RUN julia -e 'Pkg.add("DelimitedFiles")'
-RUN julia -e 'Pkg.update()'
+# https://julialang.org/juliareleases.asc
+# Julia (Binary signing key) <buildbot@julialang.org>
+ENV JULIA_GPG 3673DF529D9049477F76B37566E3C7DC03D6E495
 
+# https://julialang.org/downloads/
+ENV JULIA_VERSION 1.0.4
+
+RUN set -eux; \
+	\
+	savedAptMark="$(apt-mark showmanual)"; \
+	if ! command -v gpg > /dev/null; then \
+		apt-get update; \
+		apt-get install -y --no-install-recommends \
+			gnupg \
+			dirmngr \
+		; \
+		rm -rf /var/lib/apt/lists/*; \
+	fi; \
+	\
+# https://julialang.org/downloads/#julia-command-line-version
+# https://julialang-s3.julialang.org/bin/checksums/julia-1.0.4.sha256
+# this "case" statement is generated via "update.sh"
+	dpkgArch="$(dpkg --print-architecture)"; \
+	case "${dpkgArch##*-}" in \
+# amd64
+		amd64) tarArch='x86_64'; dirArch='x64'; sha256='bb9e33d95f47e703d9199f0358c038c61259e2ff9f3fd515c919729ace89443c' ;; \
+# arm32v7
+		armhf) tarArch='armv7l'; dirArch='armv7l'; sha256='2e742f4ddf5ac21779b6943ef210d73dc02f1c6de23836b352336a3dcbb18ae6' ;; \
+# arm64v8
+		arm64) tarArch='aarch64'; dirArch='aarch64'; sha256='7614d4239702c497330c043f37d99600b41e87caa8b92742c7104915eb54648a' ;; \
+# i386
+		i386) tarArch='i686'; dirArch='x86'; sha256='89b71a3558aa4f515becfd21d19651035d909f5f2e3177ccaec77aee01f962b7' ;; \
+		*) echo >&2 "error: current architecture ($dpkgArch) does not have a corresponding Julia binary release"; exit 1 ;; \
+	esac; \
+	\
+	folder="$(echo "$JULIA_VERSION" | cut -d. -f1-2)"; \
+	curl -fL -o julia.tar.gz.asc "https://julialang-s3.julialang.org/bin/linux/${dirArch}/${folder}/julia-${JULIA_VERSION}-linux-${tarArch}.tar.gz.asc"; \
+	curl -fL -o julia.tar.gz     "https://julialang-s3.julialang.org/bin/linux/${dirArch}/${folder}/julia-${JULIA_VERSION}-linux-${tarArch}.tar.gz"; \
+	\
+	echo "${sha256} *julia.tar.gz" | sha256sum -c -; \
+	\
+	export GNUPGHOME="$(mktemp -d)"; \
+	gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$JULIA_GPG"; \
+	gpg --batch --verify julia.tar.gz.asc julia.tar.gz; \
+	command -v gpgconf > /dev/null && gpgconf --kill all; \
+	rm -rf "$GNUPGHOME" julia.tar.gz.asc; \
+	\
+	mkdir "$JULIA_PATH"; \
+	tar -xzf julia.tar.gz -C "$JULIA_PATH" --strip-components 1; \
+	rm julia.tar.gz; \
+	\
+	apt-mark auto '.*' > /dev/null; \
+	[ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; \
+	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
+	\
+# smoke test
+	julia --version
+
+#CMD ["julia"]
 #copy contents of tasks/<taskname>/build/src on the build host into /opt/src on the docker
 COPY src/ /opt/src/
 
 WORKDIR /opt/src
-
-# Define default command.
-#CMD ["bash"]
 
